[book]
title = "OpenRR Book"
description = "Tutorial and reference for OpenRR"
src = "src"

[rust]
edition = "2021"

[output.html]
git-repository-url = "https://github.com/openrr/openrr-tutorial/tree/main/docs/en"
edit-url-template = "https://github.com/openrr/openrr-tutorial/tree/main/docs/en/{path}"

[output.linkcheck]
cache-timeout = 3600 # Set timeout to an hour
warning-policy = "ignore"
